### PR TITLE
Feat: Devops Cleanup

### PR DESCRIPTION
**Pull request by RyanWalker277**
- [x] Modified logger to take mongodbURL from the config instead of hardcoding it
- [x] cleaned up the compose:
    - [x] added a .env for secrets
    - [x] added healthcehecks
    - [x] modified existing dockerfiles for docker based setup

### CODE REVIEW

**Review by tushar5526 — COMMENTED** [review]
Any sample.env or env files for all these services? How would protocol server and protocol client will connect to redis and queue without any env vars ?

**Comment by RyanWalker277** [comment]
> Any sample.env or env files for all these services? How would protocol server and protocol client will connect to redis and queue without any env vars ?

Yeah there is a .env for this. Sharing with you over discord.

**Review by tushar5526 — APPROVED** [review]
LGTM

**Review by amit-s19 — APPROVED** [review]
LGTM

**Pull request merged**
