### PR TITLE
Feat: Changed response code for empty response to 408

### PR DESCRIPTION
**Pull request by RyanWalker277**

### CODE REVIEW

**Review by amit-s19 — COMMENTED** [review]
Is this working as we discussed? Is the syncCache.getData promise getting resolved as expected or it's getting resolved first everytime?

**Comment by RyanWalker277** [comment]
Hey @amit-s19, there were some changes in the logic. I have pushed the changes into this PR, but on my setup when I am changing the `bpp_uri` in the init curl, the `syncCache.getData` promise is still resolving which it shouldn't. It is getting data from somewhere whose source I am not sure about. Due to this I was unable to test it, would be really helpful if you could test it and let me know if the current approach works properly or not.

**Comment by RyanWalker277** [comment]
Hey @amit-s19, I have done some changes, the response is now being sent as it should. Also, I have removed the logs directory from the git tree, so they wont be tracked. Please review.

**Review by amit-s19 — APPROVED** [review]
LGTM

**Pull request merged**
